######################################################################
# Automatically generated by qmake (2.00a) Mon Jul 24 21:03:16 2006
######################################################################

TEMPLATE = app
TARGET = run_tests
DEPENDPATH += . 
INCLUDEPATH += . tests src tests/lib

# Keep object files in "build"
OBJECTS_DIR = build

# Input
HEADERS += \
           tests/lib/assertion.h \
           tests/lib/failure_exception.h \
           tests/lib/fixture.h \
           tests/lib/output_handler.h \
           tests/lib/test.h \
           tests/lib/test_registry.h \
           src/database/block_allocator.h \
           src/database/column.h \
           src/database/enumeration.h \
           src/database/misc.h \
           src/database/result_set.h \
           src/database/table.h \
           src/database.h \
           src/errors.h \
           src/file_errors.h

SOURCES += \
           tests/column_test.cpp \
           tests/database_test.cpp \
           tests/enumeration_test.cpp \
           tests/misc_test.cpp \
           tests/table_test.cpp \
           tests/lib/assertion.cpp \
           tests/lib/failure_exception.cpp \
           tests/lib/fixture.cpp \
           tests/lib/output_handler.cpp \
           tests/lib/sample_suite.cpp \
           tests/lib/test.cpp \
           tests/lib/test_registry.cpp \
           src/database/block_allocator.cpp \
           src/database/column.cpp \
           src/database/enumeration.cpp \
           src/database/misc.cpp \
           src/database/result_set.cpp \
           src/database/serialization.cpp \
           src/database/table.cpp \
           src/database.cpp \
           src/errors.cpp \
           src/file_errors.cpp

LIBXML_CFLAGS = $$system(pkg-config libxml-2.0 --cflags)
LIBXML_LIBS = $$system(pkg-config libxml-2.0 --libs)
QMAKE_CXXFLAGS += $$LIBXML_CFLAGS
LIBS += $$LIBXML_LIBS
